-- ==========================================================================
-- CareerOptics CRM — BLOCK 1 of 2: role enum values
--
-- Run this on its own and let it finish before running block 2. Postgres
-- refuses to USE a new enum value in the same transaction that ADDS it,
-- and block 2's RLS policies compare against all five of these roles.
--
-- Safe to run more than once: every CREATE is guarded, and every
-- policy, trigger and constraint is dropped before it is recreated.
--
-- Generated by scripts/build-apply-sql.py — edit the migrations, not this.
-- ==========================================================================


-- ------------------------------------------------------------------------
-- 0007_crm_roles.sql
-- ------------------------------------------------------------------------

-- CRM staff roles, added to the existing `user_role` enum so the CRM and the
-- website share one profiles table and one login rather than maintaining two.
--
-- This is its own migration on purpose: Postgres refuses to *use* a new enum
-- value in the same transaction that adds it, and 0006's RLS policies compare
-- against these. Splitting the file is what makes the values committed and
-- usable by the time 0006 runs.
alter type user_role add value if not exists 'telecaller';
alter type user_role add value if not exists 'backend';
alter type user_role add value if not exists 'finance';

-- ------------------------------------------------------------------------
-- 0009_crm_extra_roles.sql
-- ------------------------------------------------------------------------

-- Portal roles for the associates and student portals.
--
-- Its own file for the same reason 0007 is: Postgres refuses to *use* a new
-- enum value in the transaction that adds it, and 0016/0015's RLS policies
-- compare against these.
alter type user_role add value if not exists 'associate';
alter type user_role add value if not exists 'student';
