-- ==========================================================================
-- CareerOptics CRM — BLOCK 2 of 2: schema, RLS, triggers, grants
--
-- Run this only after block 1 has completed. Creates the `crm` schema and
-- everything in it: leads pipeline, students, payments, documents,
-- appointments, notifications, the student and associate portals, HRMS,
-- mentorships and revenue targets.
--
-- Safe to run more than once: every CREATE is guarded, and every
-- policy, trigger and constraint is dropped before it is recreated.
--
-- Generated by scripts/build-apply-sql.py — edit the migrations, not this.
-- ==========================================================================


-- ------------------------------------------------------------------------
-- 0008_crm_schema.sql
-- ------------------------------------------------------------------------

-- ─────────────────────────────────────────────────────────────────────────────
-- CRM — Phase 1: leads pipeline, students, fees and settings.
--
-- Ported from the DCW CRM (schema only, no data) into a dedicated `crm`
-- Postgres schema.
--
-- WHY A SEPARATE SCHEMA
-- The CRM and this website both have `leads`, `courses`, `profiles` and
-- `lead_activities`, and they are genuinely different tables:
--   • public.leads.name vs crm.leads.full_name
--   • public.leads.source is free text ('home_hero', 'college_finder', …);
--     the CRM constrains source to its own list and would REJECT those values
--   • public.courses is the 60-row SEO catalogue; crm.courses is the short
--     list of things the consultancy actually sells
-- Keeping the CRM in its own schema means none of that has to be reconciled
-- and the live website keeps working untouched.
--
-- ONE EXCEPTION: profiles. Staff should have one login and one role, so the
-- CRM reuses public.profiles and the `user_role` enum is extended rather than
-- creating a second user table.
--
-- Staff roles live in 0005_crm_roles.sql — it has to commit before the RLS
-- policies here can compare against the new enum values.
--
-- ⚠ After applying, add `crm` to Supabase → Project Settings → API →
--   "Exposed schemas", or PostgREST will not serve these tables.
-- ─────────────────────────────────────────────────────────────────────────────

create schema if not exists crm;
grant usage on schema crm to anon, authenticated, service_role;


-- ── Reference data ───────────────────────────────────────────────────────────

-- What the consultancy sells. Distinct from public.courses, which is the
-- public catalogue students browse.
create table if not exists crm.courses (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists crm.sub_courses (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references crm.courses(id) on delete cascade,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Admission session, e.g. "2026-27".
create table if not exists crm.sessions (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists crm.departments (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- University or board under a department.
create table if not exists crm.department_sub_sections (
  id uuid primary key default gen_random_uuid(),
  department_id uuid not null references crm.departments(id) on delete cascade,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ── Leads ────────────────────────────────────────────────────────────────────

create table if not exists crm.leads (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  phone text not null,
  email text,
  city text,
  state text,

  course_id uuid references crm.courses(id) on delete set null,
  sub_course_id uuid references crm.sub_courses(id) on delete set null,
  department_id uuid references crm.departments(id) on delete set null,
  sub_section_id uuid references crm.department_sub_sections(id) on delete set null,
  session_id uuid references crm.sessions(id) on delete set null,

  -- 'custom' carries a free-text label in custom_status.
  status text not null default 'new' check (status in (
    'new','contacted','interested','counselled','document_received',
    'converted','lost','dnp','switch_off','not_reachable',
    'not_interested','custom'
  )),
  custom_status text,

  -- `website` covers everything arriving from careeroptics.in. The bridge
  -- trigger records the page-level source in metadata.website_source.
  source text not null default 'website' check (source in (
    'website','walk_in','referral','whatsapp','phone','excel_import',
    'social_media','meta_ads','ivr','other'
  )),

  mode text check (mode in ('attending','non-attending')),
  assigned_to uuid references public.profiles(id) on delete set null,
  assigned_at timestamptz,
  next_followup_date date,

  total_fee numeric(12,2),
  amount_paid numeric(12,2) not null default 0,
  enrollment_date date,
  converted_at timestamptz,

  import_batch_id text,
  metadata jsonb not null default '{}'::jsonb,
  -- Set by trigger. Dedupes and matches IVR callbacks, which only ever carry
  -- the last ten digits.
  phone_last10 text,
  -- The public.leads row this came from, when it originated on the website.
  website_lead_id uuid references public.leads(id) on delete set null,

  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists crm_leads_status_idx on crm.leads (status);
create index if not exists crm_leads_assigned_idx on crm.leads (assigned_to);
create index if not exists crm_leads_created_idx on crm.leads (created_at desc);
create index if not exists crm_leads_phone10_idx on crm.leads (phone_last10);
create index if not exists crm_leads_followup_idx on crm.leads (next_followup_date);
-- Plain, not partial: ON CONFLICT cannot infer a partial index without
-- repeating its predicate, and Postgres already treats NULLs as distinct, so
-- any number of manually-created leads (website_lead_id null) coexist fine.
create unique index if not exists crm_leads_website_lead_idx
  on crm.leads (website_lead_id);

create table if not exists crm.lead_activities (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references crm.leads(id) on delete cascade,
  activity_type text not null check (activity_type in (
    'created','status_changed','assigned','transferred','note_added',
    'followup_set','payment_received','converted','document_uploaded','call_made'
  )),
  old_value text,
  new_value text,
  note text,
  performed_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists crm_lead_activities_lead_idx
  on crm.lead_activities (lead_id, created_at desc);

-- ── Students ─────────────────────────────────────────────────────────────────

create table if not exists crm.students (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid unique references crm.leads(id) on delete set null,
  enrollment_number text not null unique,
  full_name text not null,
  phone text not null,
  email text,
  city text,

  father_name text,
  guardian_name text,
  guardian_phone text,
  guardian_relationship text,

  course_id uuid references crm.courses(id) on delete set null,
  sub_course_id uuid references crm.sub_courses(id) on delete set null,
  department_id uuid references crm.departments(id) on delete set null,
  sub_section_id uuid references crm.department_sub_sections(id) on delete set null,
  session_id uuid references crm.sessions(id) on delete set null,
  mode text check (mode in ('attending','non-attending')),

  assigned_counsellor uuid references public.profiles(id) on delete set null,
  mentor_telecaller_id uuid references public.profiles(id) on delete set null,

  total_fee numeric(12,2),
  amount_paid numeric(12,2) not null default 0,
  incentive_amount numeric(10,2) default 0,
  enrollment_date date,

  -- 'pending' is the landing state for a converted lead; an admin approves it
  -- into 'active' rather than a telecaller creating live students directly.
  status text not null default 'pending' check (status in (
    'pending','active','completed','dropped','on_hold'
  )),
  drop_reason text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists crm_students_status_idx on crm.students (status);
create index if not exists crm_students_counsellor_idx on crm.students (assigned_counsellor);

-- ── Money ────────────────────────────────────────────────────────────────────

create table if not exists crm.payments (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid references crm.leads(id) on delete set null,
  student_id uuid references crm.students(id) on delete set null,
  amount numeric(12,2) not null check (amount > 0),
  payment_mode text not null check (payment_mode in (
    'cash','upi','card','neft','rtgs','cheque','other'
  )),
  payment_date date not null,
  receipt_number text,
  notes text,
  recorded_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists crm_payments_student_idx on crm.payments (student_id);
create index if not exists crm_payments_date_idx on crm.payments (payment_date desc);

create table if not exists crm.fee_structures (
  id uuid primary key default gen_random_uuid(),
  course_id uuid references crm.courses(id) on delete cascade,
  sub_course_id uuid references crm.sub_courses(id) on delete cascade,
  session_id uuid references crm.sessions(id) on delete set null,
  total_fee numeric(12,2) not null check (total_fee >= 0),
  registration_fee numeric(12,2) default 0,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ── Work ─────────────────────────────────────────────────────────────────────

create table if not exists crm.tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  assigned_to uuid references public.profiles(id) on delete cascade,
  assigned_by uuid references public.profiles(id) on delete set null,
  lead_id uuid references crm.leads(id) on delete cascade,
  student_id uuid references crm.students(id) on delete cascade,
  due_date date,
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  status text not null default 'pending' check (status in ('pending','in_progress','done')),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists crm_tasks_assignee_idx on crm.tasks (assigned_to, status);

-- ── Settings ─────────────────────────────────────────────────────────────────

-- Which fields the lead form shows, and in what order.
create table if not exists crm.lead_form_fields (
  id uuid primary key default gen_random_uuid(),
  field_key text not null unique,
  label text not null,
  field_type text not null default 'text' check (field_type in (
    'text','number','date','select','textarea','email','phone'
  )),
  is_required boolean not null default false,
  is_active boolean not null default true,
  -- System fields map to real columns and cannot be deleted, only hidden.
  is_system boolean not null default false,
  display_order int not null default 0,
  created_at timestamptz not null default now()
);

-- Per-user column choice on the leads table.
create table if not exists crm.lead_column_preferences (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  columns jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  unique (user_id)
);

-- ── Triggers ─────────────────────────────────────────────────────────────────

create or replace function crm.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists crm_leads_touch on crm.leads;
create trigger crm_leads_touch before update on crm.leads
  for each row execute function crm.touch_updated_at();
drop trigger if exists crm_students_touch on crm.students;
create trigger crm_students_touch before update on crm.students
  for each row execute function crm.touch_updated_at();

-- Last ten digits, so a +91-prefixed number and a bare one match, and an IVR
-- callback (which only ever sends ten digits) finds its lead.
create or replace function crm.set_phone_last10()
returns trigger language plpgsql as $$
begin
  new.phone_last10 := right(regexp_replace(coalesce(new.phone, ''), '\D', '', 'g'), 10);
  return new;
end;
$$;

drop trigger if exists crm_leads_phone10 on crm.leads;
create trigger crm_leads_phone10 before insert or update of phone on crm.leads
  for each row execute function crm.set_phone_last10();

-- Enrollment numbers are sequential per calendar year: CO-2026-00001.
create sequence if not exists crm.enrollment_seq;

create or replace function crm.next_enrollment_number()
returns text language sql as $$
  select 'CO-' || to_char(now(), 'YYYY') || '-' ||
         lpad(nextval('crm.enrollment_seq')::text, 5, '0');
$$;

/**
 * A lead reaching 'converted' becomes a student.
 *
 * The student lands as 'pending' rather than 'active' — conversion is a
 * telecaller's claim, and an admin approves it before the student is real.
 * Idempotent: a lead flipped back and forth does not create duplicates.
 */
create or replace function crm.handle_lead_conversion()
returns trigger language plpgsql security definer set search_path = crm, public as $$
begin
  if new.status = 'converted' and coalesce(old.status, '') <> 'converted' then
    insert into crm.students (
      lead_id, enrollment_number, full_name, phone, email, city,
      course_id, sub_course_id, department_id, sub_section_id, session_id,
      mode, assigned_counsellor, total_fee, amount_paid, enrollment_date, status
    ) values (
      new.id, crm.next_enrollment_number(), new.full_name, new.phone, new.email, new.city,
      new.course_id, new.sub_course_id, new.department_id, new.sub_section_id, new.session_id,
      new.mode, new.assigned_to, new.total_fee, new.amount_paid,
      coalesce(new.enrollment_date, current_date), 'pending'
    )
    on conflict (lead_id) do nothing;

    new.converted_at := coalesce(new.converted_at, now());

    insert into crm.lead_activities (lead_id, activity_type, new_value, performed_by)
    values (new.id, 'converted', 'converted', auth.uid());
  end if;
  return new;
end;
$$;

drop trigger if exists crm_leads_conversion on crm.leads;
create trigger crm_leads_conversion before update on crm.leads
  for each row execute function crm.handle_lead_conversion();

-- ── Bridge: website lead → CRM pipeline ──────────────────────────────────────

/**
 * Every lead the website captures becomes a CRM lead.
 *
 * The website's own `source` vocabulary ('home_hero', 'college_finder',
 * 'brochure', …) is not valid in crm.leads.source, so it is folded into
 * `website` and the original is kept in metadata.website_source. The finder's
 * six answers and the UTM set ride along in metadata too, so a telecaller sees
 * the whole funnel without joining back.
 *
 * SECURITY DEFINER because /api/leads writes as the service role and this must
 * work for an anonymous submission.
 */
create or replace function public.push_lead_to_crm()
returns trigger language plpgsql security definer set search_path = crm, public as $$
begin
  insert into crm.leads (
    full_name, phone, email, city, status, source,
    metadata, website_lead_id, created_at
  ) values (
    new.name,
    new.phone,
    nullif(new.email, ''),
    nullif(new.city, ''),
    'new',
    'website',
    jsonb_strip_nulls(jsonb_build_object(
      'website_source', new.source,
      'page_url',       new.page_url,
      'level',          new.level,
      'message',        new.message,
      'utm_source',     new.utm_source,
      'utm_medium',     new.utm_medium,
      'utm_campaign',   new.utm_campaign,
      'utm_content',    new.utm_content,
      'answers',        new.answers
    )),
    new.id,
    new.created_at
  )
  on conflict (website_lead_id) do nothing;

  return new;
end;
$$;

drop trigger if exists leads_push_to_crm on public.leads;
create trigger leads_push_to_crm after insert on public.leads
  for each row execute function public.push_lead_to_crm();

-- ── RLS ──────────────────────────────────────────────────────────────────────
-- Nothing in `crm` is public. Every table is staff-only, and a telecaller sees
-- only the leads and students they own — the same shape as the DCW CRM.

create or replace function crm.is_crm_staff()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.profiles p
     where p.id = auth.uid() and p.is_active
  );
$$;

create or replace function crm.is_manager()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.profiles p
     where p.id = auth.uid() and p.is_active
       and p.role in ('super_admin','backend','finance')
  );
$$;

do $$
declare t text;
begin
  foreach t in array array[
    'courses','sub_courses','sessions','departments','department_sub_sections',
    'leads','lead_activities','students','payments','fee_structures','tasks',
    'lead_form_fields','lead_column_preferences'
  ] loop
    execute format('alter table crm.%I enable row level security', t);
    execute format('grant select, insert, update, delete on crm.%I to authenticated', t);
  end loop;
end $$;

grant usage, select on all sequences in schema crm to authenticated;

-- Reference data: any staff member reads, managers write.
do $$
declare t text;
begin
  foreach t in array array[
    'courses','sub_courses','sessions','departments','department_sub_sections',
    'fee_structures','lead_form_fields'
  ] loop
    execute format(
      'drop policy if exists "staff read" on crm.%I', t);
    execute format(
      'create policy "staff read" on crm.%I for select to authenticated using (crm.is_crm_staff())', t);
    execute format(
      'drop policy if exists "manager write" on crm.%I', t);
    execute format(
      'create policy "manager write" on crm.%I for all to authenticated using (crm.is_manager()) with check (crm.is_manager())', t);
  end loop;
end $$;

-- Leads: managers see everything, a telecaller sees their own.
drop policy if exists "manager reads all leads" on crm.leads;
create policy "manager reads all leads" on crm.leads for select to authenticated
  using (crm.is_manager());
drop policy if exists "own leads" on crm.leads;
create policy "own leads" on crm.leads for select to authenticated
  using (assigned_to = auth.uid() or created_by = auth.uid());
drop policy if exists "staff create leads" on crm.leads;
create policy "staff create leads" on crm.leads for insert to authenticated
  with check (crm.is_crm_staff());
drop policy if exists "manager updates leads" on crm.leads;
create policy "manager updates leads" on crm.leads for update to authenticated
  using (crm.is_manager()) with check (crm.is_manager());
drop policy if exists "own leads update" on crm.leads;
create policy "own leads update" on crm.leads for update to authenticated
  using (assigned_to = auth.uid() or created_by = auth.uid())
  with check (assigned_to = auth.uid() or created_by = auth.uid());
drop policy if exists "manager deletes leads" on crm.leads;
create policy "manager deletes leads" on crm.leads for delete to authenticated
  using (crm.is_manager());

-- Activities follow the lead they belong to.
drop policy if exists "read activities" on crm.lead_activities;
create policy "read activities" on crm.lead_activities for select to authenticated
  using (crm.is_crm_staff());
drop policy if exists "write activities" on crm.lead_activities;
create policy "write activities" on crm.lead_activities for insert to authenticated
  with check (crm.is_crm_staff());

drop policy if exists "manager reads students" on crm.students;
create policy "manager reads students" on crm.students for select to authenticated
  using (crm.is_manager());
drop policy if exists "own students" on crm.students;
create policy "own students" on crm.students for select to authenticated
  using (assigned_counsellor = auth.uid() or mentor_telecaller_id = auth.uid());
drop policy if exists "staff write students" on crm.students;
create policy "staff write students" on crm.students for insert to authenticated
  with check (crm.is_crm_staff());
drop policy if exists "manager updates students" on crm.students;
create policy "manager updates students" on crm.students for update to authenticated
  using (crm.is_manager()) with check (crm.is_manager());
drop policy if exists "manager deletes students" on crm.students;
create policy "manager deletes students" on crm.students for delete to authenticated
  using (crm.is_manager());

-- Money is manager-only to read in bulk; a telecaller can still record one.
drop policy if exists "manager reads payments" on crm.payments;
create policy "manager reads payments" on crm.payments for select to authenticated
  using (crm.is_manager());
drop policy if exists "own payments" on crm.payments;
create policy "own payments" on crm.payments for select to authenticated
  using (recorded_by = auth.uid());
drop policy if exists "staff record payment" on crm.payments;
create policy "staff record payment" on crm.payments for insert to authenticated
  with check (crm.is_crm_staff());
drop policy if exists "manager updates payments" on crm.payments;
create policy "manager updates payments" on crm.payments for update to authenticated
  using (crm.is_manager()) with check (crm.is_manager());
drop policy if exists "manager deletes payments" on crm.payments;
create policy "manager deletes payments" on crm.payments for delete to authenticated
  using (crm.is_manager());

drop policy if exists "own tasks" on crm.tasks;
create policy "own tasks" on crm.tasks for select to authenticated
  using (crm.is_manager() or assigned_to = auth.uid() or assigned_by = auth.uid());
drop policy if exists "staff create tasks" on crm.tasks;
create policy "staff create tasks" on crm.tasks for insert to authenticated
  with check (crm.is_crm_staff());
drop policy if exists "own tasks update" on crm.tasks;
create policy "own tasks update" on crm.tasks for update to authenticated
  using (crm.is_manager() or assigned_to = auth.uid() or assigned_by = auth.uid())
  with check (crm.is_crm_staff());
drop policy if exists "manager deletes tasks" on crm.tasks;
create policy "manager deletes tasks" on crm.tasks for delete to authenticated
  using (crm.is_manager());

drop policy if exists "own column prefs" on crm.lead_column_preferences;
create policy "own column prefs" on crm.lead_column_preferences for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ── Seed: the field list the lead form starts from ───────────────────────────
insert into crm.lead_form_fields (field_key, label, field_type, is_required, is_system, display_order)
values
  ('full_name','Full name','text',true,true,10),
  ('phone','Phone','phone',true,true,20),
  ('email','Email','email',false,true,30),
  ('city','City','text',false,true,40),
  ('state','State','text',false,true,50),
  ('course_id','Course','select',false,true,60),
  ('sub_course_id','Sub course','select',false,true,70),
  ('session_id','Session','select',false,true,80),
  ('mode','Mode','select',false,true,100),
  ('department_id','Department','select',false,true,110),
  ('sub_section_id','University / Board','select',false,true,120),
  ('enrollment_date','Expected enrollment date','date',false,true,130),
  ('next_followup_date','Next follow-up','date',false,true,140),
  ('total_fee','Total fee','number',false,true,200),
  ('amount_paid','Amount paid','number',false,true,210)
on conflict (field_key) do nothing;

-- ------------------------------------------------------------------------
-- 0010_student_metadata.sql
-- ------------------------------------------------------------------------

-- The only column 0008 does not already declare on crm.students.
-- Everything else the CRM port needed (father_name, guardian_*, mode,
-- department_id, sub_section_id, session_id, incentive_amount) is in 0008;
-- `referred_by_associate` arrives with the associates table in 0016.
alter table crm.students
  add column if not exists metadata jsonb not null default '{}'::jsonb;

create index if not exists crm_students_metadata_idx
  on crm.students using gin (metadata);

-- ------------------------------------------------------------------------
-- 0011_student_documents_exams.sql
-- ------------------------------------------------------------------------

-- Student documents (10th marksheet, passport, visa, etc.)
create table if not exists crm.student_documents (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references crm.students(id) on delete cascade,
  doc_type text not null check (doc_type in (
    '10th_marksheet','12th_marksheet','graduation','passport',
    'sop','lor','ielts_scorecard','pte_scorecard','offer_letter','visa','other'
  )),
  status text not null default 'pending' check (status in ('pending','received','verified','rejected')),
  file_url text,
  notes text,
  expiry_date date,
  uploaded_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (student_id, doc_type)
);

create index if not exists crm_student_documents_student_idx on crm.student_documents (student_id);

-- Student exams (IELTS, PTE, etc.)
create table if not exists crm.student_exams (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references crm.students(id) on delete cascade,
  exam_type text not null check (exam_type in (
    'ielts','pte','toefl','practical','final_exam','mock_test','other'
  )),
  exam_name text not null,
  exam_date date,
  centre text,
  hall_ticket_number text,
  admit_card_url text,
  score text,
  is_passed boolean,
  remarks text,
  created_at timestamptz not null default now()
);

create index if not exists crm_student_exams_student_idx on crm.student_exams (student_id);

-- RLS. Both tables carry a student's identity documents and exam results, so
-- they follow crm.students: managers see everything, the assigned counsellor
-- or mentor sees their own, and the student sees their own via the portal.
alter table crm.student_documents enable row level security;
alter table crm.student_exams enable row level security;

drop policy if exists "manager reads documents" on crm.student_documents;
create policy "manager reads documents" on crm.student_documents for select to authenticated
  using (crm.is_manager());
drop policy if exists "own student documents" on crm.student_documents;
create policy "own student documents" on crm.student_documents for select to authenticated
  using (exists (
    select 1 from crm.students s
     where s.id = student_id
       and (s.assigned_counsellor = auth.uid() or s.mentor_telecaller_id = auth.uid())
  ));
drop policy if exists "staff write documents" on crm.student_documents;
create policy "staff write documents" on crm.student_documents for all to authenticated
  using (crm.is_manager()) with check (crm.is_crm_staff());

drop policy if exists "manager reads exams" on crm.student_exams;
create policy "manager reads exams" on crm.student_exams for select to authenticated
  using (crm.is_manager());
drop policy if exists "own student exams" on crm.student_exams;
create policy "own student exams" on crm.student_exams for select to authenticated
  using (exists (
    select 1 from crm.students s
     where s.id = student_id
       and (s.assigned_counsellor = auth.uid() or s.mentor_telecaller_id = auth.uid())
  ));
drop policy if exists "staff write exams" on crm.student_exams;
create policy "staff write exams" on crm.student_exams for all to authenticated
  using (crm.is_manager()) with check (crm.is_crm_staff());

-- ------------------------------------------------------------------------
-- 0012_appointments.sql
-- ------------------------------------------------------------------------

-- Appointments: counselor/admin bookings against a lead (office visit or Google Meet).

create table if not exists crm.appointments (
  id               uuid primary key default gen_random_uuid(),
  lead_id           uuid not null references crm.leads(id) on delete cascade,
  appointment_type  text not null check (appointment_type in ('office_visit', 'google_meet')),
  meet_link         text,
  host_id           uuid not null references public.profiles(id) on delete set null,
  created_by        uuid not null references public.profiles(id) on delete set null,
  scheduled_date    date not null,
  scheduled_time    time not null,
  duration_minutes  int not null default 30 check (duration_minutes > 0),
  status            text not null default 'scheduled'
                     check (status in ('scheduled', 'completed', 'cancelled', 'no_show')),
  notes             text,
  review_note       text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint appointments_meet_link_required check (
    appointment_type <> 'google_meet' or (meet_link is not null and btrim(meet_link) <> '')
  )
);

create index if not exists crm_appointments_lead_idx      on crm.appointments (lead_id);
create index if not exists crm_appointments_date_idx       on crm.appointments (scheduled_date);
create index if not exists crm_appointments_host_idx       on crm.appointments (host_id);

-- Slot lock: no two active bookings for the same host at the same slot.
create unique index if not exists crm_appointments_slot_unique
  on crm.appointments (host_id, scheduled_date, scheduled_time)
  where status <> 'cancelled';

create or replace function crm.set_appointments_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists crm_appointments_updated_at on crm.appointments;
create trigger crm_appointments_updated_at
  before update on crm.appointments
  for each row execute function crm.set_appointments_updated_at();

alter table crm.appointments enable row level security;

drop policy if exists "staff read appointments" on crm.appointments;
create policy "staff read appointments" on crm.appointments for select to authenticated
  using (crm.is_crm_staff());

drop policy if exists "staff insert appointments" on crm.appointments;
create policy "staff insert appointments" on crm.appointments for insert to authenticated
  with check (
    crm.is_crm_staff()
    and created_by = auth.uid()
    -- The host must be an active staff member. Any staff member can host;
    -- the enum has no separate "can be booked" role to narrow it to.
    and exists (select 1 from public.profiles where id = host_id and is_active)
  );

drop policy if exists "own appointments update" on crm.appointments;
create policy "own appointments update" on crm.appointments for update to authenticated
  using (
    host_id = auth.uid() or created_by = auth.uid() or crm.is_manager()
  )
  with check (
    host_id = auth.uid() or created_by = auth.uid() or crm.is_manager()
  );

drop policy if exists "manager delete appointments" on crm.appointments;
create policy "manager delete appointments" on crm.appointments for delete to authenticated
  using (crm.is_manager());

-- ------------------------------------------------------------------------
-- 0013_lead_capture_forms.sql
-- ------------------------------------------------------------------------

-- Lead capture forms: public-facing Meta/Facebook ad landing pages.

create table if not exists crm.lead_capture_forms (
  id                uuid primary key default gen_random_uuid(),
  slug              text unique not null,
  title             text not null,
  subtitle          text,
  fields            jsonb not null default '[]'::jsonb,
  success_message   text default 'Thank you! Our team will contact you shortly.',
  source            text not null default 'meta_ads',
  is_active         boolean not null default true,
  submissions_count integer not null default 0,
  created_by        uuid references public.profiles(id) on delete set null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index if not exists lead_capture_forms_slug_idx on crm.lead_capture_forms (slug);

alter table crm.lead_capture_forms enable row level security;

drop policy if exists "public read active forms" on crm.lead_capture_forms;
create policy "public read active forms" on crm.lead_capture_forms for select
  using (is_active = true);

drop policy if exists "admin manage forms" on crm.lead_capture_forms;
create policy "admin manage forms" on crm.lead_capture_forms for all
  using (crm.is_manager())
  with check (crm.is_manager());

create or replace function public.set_lcf_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists lcf_updated_at on crm.lead_capture_forms;
create trigger lcf_updated_at
  before update on crm.lead_capture_forms
  for each row execute function public.set_lcf_updated_at();

-- ------------------------------------------------------------------------
-- 0014_notifications.sql
-- ------------------------------------------------------------------------

-- Notifications: admin broadcasts and targeted messages.
-- dcwcrm keeps these in public because non-CRM staff also need to read them.

create table if not exists crm.notifications (
  id          uuid primary key default gen_random_uuid(),
  title       text not null,
  message     text not null,
  type        text not null default 'info'
              check (type in ('info', 'warning', 'success', 'alert')),
  target_role text,
  target_user_id uuid references public.profiles(id) on delete cascade,
  created_by  uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now()
);

create table if not exists crm.notification_reads (
  id              uuid primary key default gen_random_uuid(),
  notification_id uuid not null references crm.notifications(id) on delete cascade,
  user_id         uuid not null references public.profiles(id) on delete cascade,
  read_at         timestamptz default now(),
  unique (notification_id, user_id)
);

create index if not exists idx_notifications_target_user on crm.notifications (target_user_id);
create index if not exists idx_notifications_target_role on crm.notifications (target_role);
create index if not exists idx_notifications_created on crm.notifications (created_at desc);

alter table crm.notifications enable row level security;
alter table crm.notification_reads enable row level security;

drop policy if exists "authenticated read notifications" on crm.notifications;
create policy "authenticated read notifications" on crm.notifications for select
  using (auth.uid() is not null);

drop policy if exists "admin insert notifications" on crm.notifications;
create policy "admin insert notifications" on crm.notifications for insert
  with check (
    crm.is_manager()
  );

drop policy if exists "own notification reads" on crm.notification_reads;
create policy "own notification reads" on crm.notification_reads for select
  using (auth.uid() = user_id);

drop policy if exists "own notification read insert" on crm.notification_reads;
create policy "own notification read insert" on crm.notification_reads for insert
  with check (auth.uid() = user_id);

-- ------------------------------------------------------------------------
-- 0015_student_portal.sql
-- ------------------------------------------------------------------------

-- Student portal columns on crm.students
ALTER TABLE crm.students
  ADD COLUMN IF NOT EXISTS portal_user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS portal_username text,
  ADD COLUMN IF NOT EXISTS portal_temp_password text,
  ADD COLUMN IF NOT EXISTS portal_active boolean not null default false,
  ADD COLUMN IF NOT EXISTS university_name text,
  ADD COLUMN IF NOT EXISTS board_name text,
  ADD COLUMN IF NOT EXISTS father_name text,
  ADD COLUMN IF NOT EXISTS guardian_name text,
  ADD COLUMN IF NOT EXISTS guardian_phone text,
  ADD COLUMN IF NOT EXISTS guardian_relationship text,
  ADD COLUMN IF NOT EXISTS dob date,
  ADD COLUMN IF NOT EXISTS gender text CHECK (gender IN ('male','female','other')),
  ADD COLUMN IF NOT EXISTS address text,
  ADD COLUMN IF NOT EXISTS state text,
  ADD COLUMN IF NOT EXISTS pincode text,
  ADD COLUMN IF NOT EXISTS verification_status text NOT NULL DEFAULT 'pending'
    CHECK (verification_status IN ('pending','in_review','verified','rejected')),
  ADD COLUMN IF NOT EXISTS exam_status text NOT NULL DEFAULT 'not_scheduled'
    CHECK (exam_status IN ('not_scheduled','scheduled','completed','result_awaited','passed','failed')),
  ADD COLUMN IF NOT EXISTS result_status text NOT NULL DEFAULT 'awaited'
    CHECK (result_status IN ('awaited','declared','passed','failed','re_appear')),
  ADD COLUMN IF NOT EXISTS admit_card_url text,
  ADD COLUMN IF NOT EXISTS enrollment_card_url text,
  ADD COLUMN IF NOT EXISTS id_card_url text,
  ADD COLUMN IF NOT EXISTS marksheet_url text,
  ADD COLUMN IF NOT EXISTS certificate_url text,
  ADD COLUMN IF NOT EXISTS profile_photo_url text,
  ADD COLUMN IF NOT EXISTS admission_progress int NOT NULL DEFAULT 0 CHECK (admission_progress BETWEEN 0 AND 100);

CREATE UNIQUE INDEX IF NOT EXISTS crm_students_portal_user_idx ON crm.students(portal_user_id) WHERE portal_user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS crm_students_portal_active_idx ON crm.students(portal_active);

-- Student notifications
CREATE TABLE IF NOT EXISTS crm.student_notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid REFERENCES crm.students(id) ON DELETE CASCADE,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL DEFAULT 'info' CHECK (type IN ('info','success','warning','alert')),
  file_url text,
  category text,
  is_read boolean NOT NULL DEFAULT false,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS crm_student_notif_student_idx ON crm.student_notifications(student_id);
CREATE INDEX IF NOT EXISTS crm_student_notif_read_idx ON crm.student_notifications(student_id, is_read);

-- Student announcements
CREATE TABLE IF NOT EXISTS crm.student_announcements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  body text NOT NULL,
  type text NOT NULL DEFAULT 'general' CHECK (type IN ('general','exam','result','fee','urgent')),
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz
);
CREATE INDEX IF NOT EXISTS crm_announcements_active_idx ON crm.student_announcements(is_active, created_at DESC);

-- Student support tickets
CREATE TABLE IF NOT EXISTS crm.student_support_tickets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL REFERENCES crm.students(id) ON DELETE CASCADE,
  subject text NOT NULL,
  message text NOT NULL,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','in_progress','resolved','closed')),
  priority text NOT NULL DEFAULT 'normal' CHECK (priority IN ('low','normal','high','urgent')),
  admin_reply text,
  replied_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  replied_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS crm_tickets_student_idx ON crm.student_support_tickets(student_id);
CREATE INDEX IF NOT EXISTS crm_tickets_status_idx ON crm.student_support_tickets(status);

-- Study materials
CREATE TABLE IF NOT EXISTS crm.study_materials (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  type text NOT NULL DEFAULT 'pdf' CHECK (type IN ('ebook','pdf_notes','syllabus','recorded_class','live_class','other')),
  url text,
  course_id uuid REFERENCES crm.courses(id) ON DELETE SET NULL,
  sub_course_id uuid REFERENCES crm.sub_courses(id) ON DELETE SET NULL,
  is_active boolean NOT NULL DEFAULT true,
  uploaded_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS crm_materials_course_idx ON crm.study_materials(course_id, is_active);
CREATE INDEX IF NOT EXISTS crm_materials_type_idx ON crm.study_materials(type, is_active);

-- Student FAQs
CREATE TABLE IF NOT EXISTS crm.student_faqs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  question text NOT NULL,
  answer text NOT NULL,
  category text NOT NULL DEFAULT 'general',
  sort_order int NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- RLS
ALTER TABLE crm.student_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm.student_announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm.student_support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm.study_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm.student_faqs ENABLE ROW LEVEL SECURITY;

-- Admin/backend: full access
drop policy if exists "admin_student_notif" on crm.student_notifications;
CREATE POLICY "admin_student_notif" ON crm.student_notifications FOR ALL
  USING (crm.is_manager());
drop policy if exists "admin_announcements" on crm.student_announcements;
CREATE POLICY "admin_announcements" ON crm.student_announcements FOR ALL
  USING (crm.is_manager());
drop policy if exists "admin_tickets" on crm.student_support_tickets;
CREATE POLICY "admin_tickets" ON crm.student_support_tickets FOR ALL
  USING (crm.is_manager());
drop policy if exists "admin_materials" on crm.study_materials;
CREATE POLICY "admin_materials" ON crm.study_materials FOR ALL
  USING (crm.is_manager());
drop policy if exists "admin_faqs" on crm.student_faqs;
CREATE POLICY "admin_faqs" ON crm.student_faqs FOR ALL
  USING (crm.is_manager());

-- Students: own notifications (read + mark read)
drop policy if exists "student_own_notif" on crm.student_notifications;
CREATE POLICY "student_own_notif" ON crm.student_notifications FOR SELECT
  USING (student_id IN (SELECT id FROM crm.students WHERE portal_user_id = auth.uid()));
drop policy if exists "student_mark_notif_read" on crm.student_notifications;
CREATE POLICY "student_mark_notif_read" ON crm.student_notifications FOR UPDATE
  USING (student_id IN (SELECT id FROM crm.students WHERE portal_user_id = auth.uid()));

-- Students: announcements
drop policy if exists "student_view_announcements" on crm.student_announcements;
CREATE POLICY "student_view_announcements" ON crm.student_announcements FOR SELECT
  USING (is_active = true AND (expires_at IS NULL OR expires_at > now()));

-- Students: own tickets
drop policy if exists "student_own_tickets" on crm.student_support_tickets;
CREATE POLICY "student_own_tickets" ON crm.student_support_tickets FOR SELECT
  USING (student_id IN (SELECT id FROM crm.students WHERE portal_user_id = auth.uid()));
drop policy if exists "student_create_tickets" on crm.student_support_tickets;
CREATE POLICY "student_create_tickets" ON crm.student_support_tickets FOR INSERT
  WITH CHECK (student_id IN (SELECT id FROM crm.students WHERE portal_user_id = auth.uid()));

-- Students: active materials for their course
drop policy if exists "student_view_materials" on crm.study_materials;
CREATE POLICY "student_view_materials" ON crm.study_materials FOR SELECT
  USING (
    is_active = true AND (
      course_id IS NULL
      OR course_id IN (SELECT course_id FROM crm.students WHERE portal_user_id = auth.uid() AND course_id IS NOT NULL)
    )
  );

-- Students: FAQs
drop policy if exists "student_view_faqs" on crm.student_faqs;
CREATE POLICY "student_view_faqs" ON crm.student_faqs FOR SELECT
  USING (is_active = true);

-- Students: own student record
drop policy if exists "student_read_own" on crm.students;
CREATE POLICY "student_read_own" ON crm.students FOR SELECT
  USING (portal_user_id = auth.uid());
drop policy if exists "student_update_own_profile" on crm.students;
CREATE POLICY "student_update_own_profile" ON crm.students FOR UPDATE
  USING (portal_user_id = auth.uid())
  WITH CHECK (portal_user_id = auth.uid());

-- Students: own payments
drop policy if exists "student_own_payments" on crm.payments;
CREATE POLICY "student_own_payments" ON crm.payments FOR SELECT
  USING (student_id IN (SELECT id FROM crm.students WHERE portal_user_id = auth.uid()));

-- Seed FAQs
INSERT INTO crm.student_faqs (question, answer, category, sort_order) VALUES
  ('How do I check my admission status?', 'Go to "My Admission Status" section in the portal to see your complete admission progress including verification, exam, and result status.', 'admission', 1),
  ('How can I download my admit card?', 'Once your admit card is issued, it will appear in the "My Admission Status" section under "Documents". You can download it from there.', 'exam', 2),
  ('Where can I see my payment history?', 'Go to "Accounts" section to view your complete payment history, pending dues, and download receipts.', 'payment', 3),
  ('How do I raise a support ticket?', 'Go to "Help & Support" section and click "Raise a Ticket". Our team will respond within 24-48 hours.', 'support', 4),
  ('How do I update my contact information?', 'Go to "Profile" section and click on "Contact Information" to update your phone number, email, or address.', 'profile', 5)
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------------------
-- 0016_associates_portal.sql
-- ------------------------------------------------------------------------

-- Associates portal: referral partners who bring in students/leads.

create table if not exists crm.associates (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null,
  father_phone text,
  email text not null unique,
  aadhar_number text,
  pan_number text,
  current_address text,
  current_city text,
  current_state text,
  current_pincode text,
  permanent_address text,
  permanent_city text,
  permanent_state text,
  permanent_pincode text,
  same_as_current boolean not null default false,
  bank_name text,
  account_number text,
  ifsc_code text,
  account_holder_name text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  associate_code text unique,
  user_id uuid references public.profiles(id) on delete set null,
  wallet_balance numeric not null default 0,
  rejection_reason text,
  coordinator_id uuid references public.profiles(id) on delete set null,
  coordinator_name text,
  temp_password text,
  aadhar_doc_url text,
  pan_doc_url text,
  cheque_doc_url text,
  state text,
  district text,
  city text,
  institution_name text,
  institution_address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  approved_at timestamptz,
  approved_by uuid references public.profiles(id) on delete set null
);

create table if not exists crm.associate_wallet_txns (
  id uuid primary key default gen_random_uuid(),
  associate_id uuid not null references crm.associates(id) on delete cascade,
  type text not null check (type in ('credit', 'debit')),
  amount numeric not null,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists crm.associate_notifications (
  id uuid primary key default gen_random_uuid(),
  associate_id uuid references crm.associates(id) on delete cascade,
  title text not null,
  message text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists crm.associate_dispatches (
  id uuid primary key default gen_random_uuid(),
  associate_id uuid not null references crm.associates(id) on delete cascade,
  item_name text not null,
  quantity int not null default 1,
  tracking_number text,
  status text not null default 'processing' check (status in ('processing', 'shipped', 'delivered')),
  dispatched_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists crm.wallet_recharge_requests (
  id uuid primary key default gen_random_uuid(),
  associate_id uuid not null references crm.associates(id) on delete cascade,
  amount numeric not null,
  receipt_url text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  rejection_reason text,
  approved_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  approved_at timestamptz
);

create table if not exists crm.associate_resources (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  type text not null default 'other'
    check (type in ('brochure','fee_structure','admission_form','marketing','poster','reel','training','other')),
  url text not null,
  file_size text,
  is_active boolean not null default true,
  uploaded_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists crm.associate_support_tickets (
  id uuid primary key default gen_random_uuid(),
  associate_id uuid not null references crm.associates(id) on delete cascade,
  subject text not null,
  message text not null,
  status text not null default 'open'
    check (status in ('open','in_progress','resolved','closed')),
  priority text not null default 'normal'
    check (priority in ('low','normal','high','urgent')),
  admin_reply text,
  replied_by uuid references public.profiles(id) on delete set null,
  replied_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists crm_associates_user_idx on crm.associates(user_id) where user_id is not null;
create index if not exists crm_associates_status_idx on crm.associates(status);
create index if not exists crm_assoc_wallet_assoc_idx on crm.associate_wallet_txns(associate_id);
create index if not exists crm_assoc_notif_assoc_idx on crm.associate_notifications(associate_id);
create index if not exists crm_assoc_dispatch_assoc_idx on crm.associate_dispatches(associate_id);
create index if not exists crm_assoc_resources_type_idx on crm.associate_resources(type, is_active);
create index if not exists crm_assoc_tickets_assoc_idx on crm.associate_support_tickets(associate_id);
create index if not exists crm_assoc_tickets_status_idx on crm.associate_support_tickets(status);
create index if not exists crm_recharge_assoc_idx on crm.wallet_recharge_requests(associate_id);

alter table crm.associates enable row level security;
alter table crm.associate_wallet_txns enable row level security;
alter table crm.associate_notifications enable row level security;
alter table crm.associate_dispatches enable row level security;
alter table crm.wallet_recharge_requests enable row level security;
alter table crm.associate_resources enable row level security;
alter table crm.associate_support_tickets enable row level security;

-- Associates read own, admin manages all
drop policy if exists "admin_associates_all" on crm.associates;
CREATE POLICY "admin_associates_all" ON crm.associates FOR ALL
  USING (crm.is_manager())
  WITH CHECK (crm.is_manager());
drop policy if exists "associate_read_own" on crm.associates;
CREATE POLICY "associate_read_own" ON crm.associates FOR SELECT
  USING (user_id = auth.uid());
drop policy if exists "associate_update_own" on crm.associates;
CREATE POLICY "associate_update_own" ON crm.associates FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

drop policy if exists "admin_wallet_all" on crm.associate_wallet_txns;
CREATE POLICY "admin_wallet_all" ON crm.associate_wallet_txns FOR ALL
  USING (crm.is_manager())
  WITH CHECK (crm.is_manager());
drop policy if exists "associate_read_wallet" on crm.associate_wallet_txns;
CREATE POLICY "associate_read_wallet" ON crm.associate_wallet_txns FOR SELECT
  USING (associate_id IN (SELECT id FROM crm.associates WHERE user_id = auth.uid()));

drop policy if exists "admin_notif_all" on crm.associate_notifications;
CREATE POLICY "admin_notif_all" ON crm.associate_notifications FOR ALL
  USING (crm.is_manager())
  WITH CHECK (crm.is_manager());
drop policy if exists "associate_read_notif" on crm.associate_notifications;
CREATE POLICY "associate_read_notif" ON crm.associate_notifications FOR SELECT
  USING (associate_id IN (SELECT id FROM crm.associates WHERE user_id = auth.uid()));
drop policy if exists "associate_mark_notif" on crm.associate_notifications;
CREATE POLICY "associate_mark_notif" ON crm.associate_notifications FOR UPDATE
  USING (associate_id IN (SELECT id FROM crm.associates WHERE user_id = auth.uid()));

drop policy if exists "admin_dispatch_all" on crm.associate_dispatches;
CREATE POLICY "admin_dispatch_all" ON crm.associate_dispatches FOR ALL
  USING (crm.is_manager())
  WITH CHECK (crm.is_manager());
drop policy if exists "associate_read_dispatch" on crm.associate_dispatches;
CREATE POLICY "associate_read_dispatch" ON crm.associate_dispatches FOR SELECT
  USING (associate_id IN (SELECT id FROM crm.associates WHERE user_id = auth.uid()));

drop policy if exists "admin_recharge_all" on crm.wallet_recharge_requests;
CREATE POLICY "admin_recharge_all" ON crm.wallet_recharge_requests FOR ALL
  USING (crm.is_manager())
  WITH CHECK (crm.is_manager());
drop policy if exists "associate_read_recharge" on crm.wallet_recharge_requests;
CREATE POLICY "associate_read_recharge" ON crm.wallet_recharge_requests FOR SELECT
  USING (associate_id IN (SELECT id FROM crm.associates WHERE user_id = auth.uid()));

drop policy if exists "admin_resources_all" on crm.associate_resources;
CREATE POLICY "admin_resources_all" ON crm.associate_resources FOR ALL
  USING (crm.is_manager())
  WITH CHECK (crm.is_manager());
drop policy if exists "associate_read_resources" on crm.associate_resources;
CREATE POLICY "associate_read_resources" ON crm.associate_resources FOR SELECT
  USING (is_active = true AND EXISTS (SELECT 1 FROM crm.associates WHERE user_id = auth.uid()));

drop policy if exists "associate_tickets_all" on crm.associate_support_tickets;
CREATE POLICY "associate_tickets_all" ON crm.associate_support_tickets FOR ALL
  USING (associate_id IN (SELECT id FROM crm.associates WHERE user_id = auth.uid()))
  WITH CHECK (associate_id IN (SELECT id FROM crm.associates WHERE user_id = auth.uid()));
drop policy if exists "admin_tickets_all" on crm.associate_support_tickets;
CREATE POLICY "admin_tickets_all" ON crm.associate_support_tickets FOR ALL
  USING (crm.is_manager())
  WITH CHECK (crm.is_manager());

-- Link leads/students to the associate who referred them
ALTER TABLE crm.leads
  ADD COLUMN IF NOT EXISTS referred_by_associate uuid REFERENCES crm.associates(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS crm_leads_referred_assoc_idx ON crm.leads(referred_by_associate);

ALTER TABLE crm.students
  ADD COLUMN IF NOT EXISTS referred_by_associate uuid REFERENCES crm.associates(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS crm_students_referred_assoc_idx ON crm.students(referred_by_associate) WHERE referred_by_associate IS NOT NULL;

-- ------------------------------------------------------------------------
-- 0017_dispatches_uploads.sql
-- ------------------------------------------------------------------------

-- Student document dispatch tracking
CREATE TABLE IF NOT EXISTS crm.student_dispatches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_name text NOT NULL,
  enrollment_number text,
  associate_id uuid REFERENCES crm.associates(id) ON DELETE SET NULL,
  document_type text NOT NULL DEFAULT 'marksheet',
  dispatch_type text NOT NULL DEFAULT 'outbound'
    CHECK (dispatch_type IN ('inbound', 'outbound')),
  courier text,
  tracking_number text,
  dispatch_date date,
  expected_delivery date,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','dispatched','in_transit','delivered','returned','failed')),
  remarks text,
  student_phone text,
  father_name text,
  dispatched_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS crm_dispatches_assoc_idx ON crm.student_dispatches(associate_id);
CREATE INDEX IF NOT EXISTS crm_dispatches_status_idx ON crm.student_dispatches(status);
CREATE INDEX IF NOT EXISTS crm_dispatches_created_idx ON crm.student_dispatches(created_at DESC);
CREATE INDEX IF NOT EXISTS crm_dispatches_type_idx ON crm.student_dispatches(dispatch_type);

ALTER TABLE crm.student_dispatches ENABLE ROW LEVEL SECURITY;

drop policy if exists "admin_full_dispatch" on crm.student_dispatches;
CREATE POLICY "admin_full_dispatch" ON crm.student_dispatches FOR ALL
  USING (crm.is_manager())
  WITH CHECK (crm.is_manager());

-- Student-uploaded documents
CREATE TABLE IF NOT EXISTS crm.student_uploads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL REFERENCES crm.students(id) ON DELETE CASCADE,
  document_type text NOT NULL,
  file_url text NOT NULL,
  remarks text,
  uploaded_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS crm_student_uploads_student_idx ON crm.student_uploads(student_id, uploaded_at DESC);

ALTER TABLE crm.student_uploads ENABLE ROW LEVEL SECURITY;

drop policy if exists "admin_student_uploads" on crm.student_uploads;
CREATE POLICY "admin_student_uploads" ON crm.student_uploads FOR ALL
  USING (crm.is_manager())
  WITH CHECK (crm.is_manager());

drop policy if exists "student_own_uploads_select" on crm.student_uploads;
CREATE POLICY "student_own_uploads_select" ON crm.student_uploads FOR SELECT
  USING (student_id IN (SELECT id FROM crm.students WHERE portal_user_id = auth.uid()));

drop policy if exists "student_own_uploads_insert" on crm.student_uploads;
CREATE POLICY "student_own_uploads_insert" ON crm.student_uploads FOR INSERT
  WITH CHECK (student_id IN (SELECT id FROM crm.students WHERE portal_user_id = auth.uid()));

-- ------------------------------------------------------------------------
-- 0018_payroll.sql
-- ------------------------------------------------------------------------

-- Payroll table

create table if not exists crm.payroll (
  id uuid primary key default gen_random_uuid(),
  -- FK added in 0019, once crm.employees exists.
  employee_id uuid not null,
  month integer not null check (month between 1 and 12),
  year integer not null,
  basic numeric(12,2) not null default 0,
  hra numeric(12,2) not null default 0,
  allowances numeric(12,2) not null default 0,
  incentive numeric(12,2) not null default 0,
  gross numeric(12,2) not null default 0,
  pf numeric(12,2) not null default 0,
  tds numeric(12,2) not null default 0,
  other_deductions numeric(12,2) not null default 0,
  advance_deduction numeric(10,2) not null default 0,
  net numeric(12,2) not null default 0,
  status text not null default 'draft' check (status in ('draft','processed','paid')),
  payment_date date,
  created_at timestamptz not null default now(),
  unique (employee_id, month, year)
);

create index if not exists payroll_emp_idx on crm.payroll(employee_id);
create index if not exists payroll_status_idx on crm.payroll(status);

alter table crm.payroll enable row level security;

drop policy if exists "admin_manage_payroll" on crm.payroll;
create policy "admin_manage_payroll" on crm.payroll for all
  using (crm.is_manager())
  with check (crm.is_manager());

-- The self-service read policy is created in 0019 with crm.employees.

-- ------------------------------------------------------------------------
-- 0019_hrms_employees.sql
-- ------------------------------------------------------------------------

-- HRMS: Employees, Attendance, Leave Requests, Expenses, Advance Salaries

-- =====================================================================
-- EMPLOYEES
-- =====================================================================
create table if not exists crm.employees (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade unique,
  employee_code text not null unique,
  department text,
  designation text,
  joining_date date,
  basic_salary numeric(12,2) default 0,
  hra numeric(12,2) default 0,
  allowances numeric(12,2) default 0,
  incentive numeric(12,2) default 0,
  pf_deduction numeric(12,2) default 0,
  tds_deduction numeric(12,2) default 0,
  other_deductions numeric(12,2) default 0,
  bank_account text,
  bank_ifsc text,
  bank_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists employees_profile_idx on crm.employees(profile_id);
create index if not exists employees_code_idx on crm.employees(employee_code);

alter table crm.employees enable row level security;

drop policy if exists "admin_manage_employees" on crm.employees;
create policy "admin_manage_employees" on crm.employees for all
  using (crm.is_manager())
  with check (crm.is_manager());

drop policy if exists "employee_read_own" on crm.employees;
create policy "employee_read_own" on crm.employees for select
  using (profile_id = auth.uid());

-- =====================================================================
-- ATTENDANCE
-- =====================================================================
create table if not exists crm.attendance (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references crm.employees(id) on delete cascade,
  date date not null,
  status text not null check (status in ('present','absent','half_day','late','leave','holiday')),
  clock_in time,
  clock_out time,
  notes text,
  marked_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (employee_id, date)
);

create index if not exists attendance_emp_date_idx on crm.attendance(employee_id, date);

alter table crm.attendance enable row level security;

drop policy if exists "admin_manage_attendance" on crm.attendance;
create policy "admin_manage_attendance" on crm.attendance for all
  using (crm.is_manager());

drop policy if exists "employee_read_own_attendance" on crm.attendance;
create policy "employee_read_own_attendance" on crm.attendance for select
  using (exists (select 1 from crm.employees where id = employee_id and profile_id = auth.uid()));

-- =====================================================================
-- LEAVE REQUESTS
-- =====================================================================
create table if not exists crm.leave_requests (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references crm.employees(id) on delete cascade,
  leave_type text not null check (leave_type in ('sick','casual','earned','unpaid','other')),
  from_date date not null,
  to_date date not null,
  reason text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  approved_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists leave_req_emp_idx on crm.leave_requests(employee_id);
create index if not exists leave_req_status_idx on crm.leave_requests(status);

alter table crm.leave_requests enable row level security;

drop policy if exists "admin_manage_leaves" on crm.leave_requests;
create policy "admin_manage_leaves" on crm.leave_requests for all
  using (crm.is_manager());

drop policy if exists "employee_own_leaves" on crm.leave_requests;
create policy "employee_own_leaves" on crm.leave_requests for all
  using (exists (select 1 from crm.employees where id = employee_id and profile_id = auth.uid()))
  with check (exists (select 1 from crm.employees where id = employee_id and profile_id = auth.uid()));

-- =====================================================================
-- EXPENSES
-- =====================================================================
create table if not exists crm.expenses (
  id uuid primary key default gen_random_uuid(),
  category text not null check (category in (
    'rent','utilities','marketing','travel','salary','vendor','misc','other'
  )),
  description text not null,
  amount numeric(12,2) not null check (amount > 0),
  expense_date date not null,
  payment_mode text,
  bill_url text,
  notes text,
  submitted_by uuid references public.profiles(id) on delete set null,
  approved_by uuid references public.profiles(id) on delete set null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

create index if not exists expenses_status_idx on crm.expenses(status);
create index if not exists expenses_submitted_idx on crm.expenses(submitted_by);

alter table crm.expenses enable row level security;

drop policy if exists "finance_admin_view_expenses" on crm.expenses;
create policy "finance_admin_view_expenses" on crm.expenses for select
  using (crm.is_manager());

drop policy if exists "staff_submit_expenses" on crm.expenses;
create policy "staff_submit_expenses" on crm.expenses for insert
  with check (auth.uid() is not null);

drop policy if exists "finance_admin_update_expenses" on crm.expenses;
create policy "finance_admin_update_expenses" on crm.expenses for update
  using (crm.is_manager());

-- =====================================================================
-- ADVANCE SALARIES
-- =====================================================================
create table if not exists crm.advance_salaries (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references crm.employees(id) on delete cascade,
  amount numeric(10,2) not null check (amount > 0),
  given_on date not null default current_date,
  reason text,
  status text not null default 'pending' check (status in ('pending','settled','cancelled')),
  settled_in uuid references crm.payroll(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists advance_sal_emp_idx on crm.advance_salaries(employee_id);

alter table crm.advance_salaries enable row level security;

drop policy if exists "admin_manage_advance" on crm.advance_salaries;
create policy "admin_manage_advance" on crm.advance_salaries for all
  using (crm.is_manager())
  with check (crm.is_manager());

drop policy if exists "employee_read_own_advance" on crm.advance_salaries;
create policy "employee_read_own_advance" on crm.advance_salaries for select
  using (exists (select 1 from crm.employees where id = employee_id and profile_id = auth.uid()));

-- ── Deferred from 0018 ───────────────────────────────────────────────────────
-- crm.payroll is created first (advance_salaries.settled_in points at it), so
-- the two links back to crm.employees are closed here instead.
alter table crm.payroll drop constraint if exists payroll_employee_fk;
alter table crm.payroll
  add constraint payroll_employee_fk
  foreign key (employee_id) references crm.employees(id) on delete cascade;

drop policy if exists "employee_read_own_payroll" on crm.payroll;
create policy "employee_read_own_payroll" on crm.payroll for select
  using (exists (select 1 from crm.employees where id = employee_id and profile_id = auth.uid()));

-- ------------------------------------------------------------------------
-- 0020_department_litigations.sql
-- ------------------------------------------------------------------------

-- Department litigation tracking system

-- Add dept_fund column to departments (manually updated balance)
ALTER TABLE crm.departments ADD COLUMN IF NOT EXISTS dept_fund NUMERIC(12,2) DEFAULT 0;

-- Create department_litigations table
CREATE TABLE IF NOT EXISTS crm.department_litigations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  department_id UUID NOT NULL REFERENCES crm.departments(id) ON DELETE CASCADE,
  sub_section_id UUID REFERENCES crm.department_sub_sections(id) ON DELETE SET NULL,
  session_id UUID REFERENCES crm.sessions(id) ON DELETE SET NULL,
  student_name TEXT NOT NULL,
  father_name TEXT,
  phone TEXT,
  litigation_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  amount_paid NUMERIC(12,2) NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Updated_at trigger
CREATE OR REPLACE FUNCTION crm.update_litigation_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS litigation_updated_at ON crm.department_litigations;
CREATE TRIGGER litigation_updated_at
  BEFORE UPDATE ON crm.department_litigations
  FOR EACH ROW EXECUTE FUNCTION crm.update_litigation_updated_at();

-- RLS
ALTER TABLE crm.department_litigations ENABLE ROW LEVEL SECURITY;

drop policy if exists "crm_staff_view_litigations" on crm.department_litigations;
CREATE POLICY "crm_staff_view_litigations" ON crm.department_litigations FOR SELECT
  USING (crm.is_manager());

drop policy if exists "admin_manage_litigations" on crm.department_litigations;
CREATE POLICY "admin_manage_litigations" ON crm.department_litigations FOR ALL
  USING (crm.is_manager())
  WITH CHECK (crm.is_manager());

-- ------------------------------------------------------------------------
-- 0021_student_mentorships.sql
-- ------------------------------------------------------------------------

-- Student mentorship: admin assigns telecallers to students for follow-up work

CREATE TABLE IF NOT EXISTS crm.student_mentorships (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id    UUID NOT NULL REFERENCES crm.students(id) ON DELETE CASCADE,
  telecaller_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  task_type     TEXT NOT NULL CHECK (task_type IN ('work_assignment', 'practical', 'exam')),
  description   TEXT,
  rating        NUMERIC(3,1) CHECK (rating >= 0 AND rating <= 10),

  -- Admin approval fields
  status           TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected')),
  salary_percentage NUMERIC(5,2),
  admin_remarks    TEXT,
  approved_by      UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  approved_at      TIMESTAMPTZ,

  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sm_student    ON crm.student_mentorships(student_id);
CREATE INDEX IF NOT EXISTS idx_sm_telecaller ON crm.student_mentorships(telecaller_id);
CREATE INDEX IF NOT EXISTS idx_sm_status     ON crm.student_mentorships(status);

ALTER TABLE crm.student_mentorships ENABLE ROW LEVEL SECURITY;

-- Admin/backend: full access
drop policy if exists "admin_mentorships_all" on crm.student_mentorships;
CREATE POLICY "admin_mentorships_all" ON crm.student_mentorships FOR ALL
  USING (crm.is_manager());

-- Telecallers: can read mentorships assigned to them
drop policy if exists "telecaller_view_own" on crm.student_mentorships;
CREATE POLICY "telecaller_view_own" ON crm.student_mentorships FOR SELECT
  USING (telecaller_id = auth.uid());

-- ------------------------------------------------------------------------
-- 0022_revenue_targets.sql
-- ------------------------------------------------------------------------

-- Revenue targets: assign monetary/lead targets to counsellors with bonus config

CREATE TABLE IF NOT EXISTS crm.revenue_targets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  assignee_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL DEFAULT 'Revenue Target',
  target_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (target_amount >= 0),
  lead_target INTEGER NOT NULL DEFAULT 0 CHECK (lead_target >= 0),
  conversion_target INTEGER NOT NULL DEFAULT 0 CHECK (conversion_target >= 0),
  period_type TEXT NOT NULL DEFAULT 'monthly' CHECK (period_type IN ('daily','weekly','monthly','quarterly','custom')),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  bonus_percentage NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (bonus_percentage >= 0),
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','archived')),
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT revenue_targets_valid_dates CHECK (end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS idx_rev_targets_assignee ON crm.revenue_targets(assignee_id);
CREATE INDEX IF NOT EXISTS idx_rev_targets_dates ON crm.revenue_targets(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_rev_targets_status ON crm.revenue_targets(status);

CREATE OR REPLACE FUNCTION crm.set_revenue_targets_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS revenue_targets_updated_at ON crm.revenue_targets;
CREATE TRIGGER revenue_targets_updated_at
  BEFORE UPDATE ON crm.revenue_targets
  FOR EACH ROW EXECUTE FUNCTION crm.set_revenue_targets_updated_at();

ALTER TABLE crm.revenue_targets ENABLE ROW LEVEL SECURITY;

drop policy if exists "admin_manage_revenue_targets" on crm.revenue_targets;
CREATE POLICY "admin_manage_revenue_targets"
  ON crm.revenue_targets FOR ALL
  USING (crm.is_manager())
  WITH CHECK (crm.is_manager());

drop policy if exists "counsellor_view_own_targets" on crm.revenue_targets;
CREATE POLICY "counsellor_view_own_targets"
  ON crm.revenue_targets FOR SELECT
  USING (assignee_id = auth.uid());

-- ------------------------------------------------------------------------
-- 0023_crm_grants.sql
-- ------------------------------------------------------------------------

-- PostgREST talks to these tables as `authenticated`, and a table with RLS on
-- but no GRANT denies every request before a policy is even consulted. 0008
-- granted its own thirteen tables; everything added in 0011–0022 needs the
-- same, or every new CRM screen returns an empty list with no error.
do $$
declare t text;
begin
  foreach t in array array[
    'student_documents','student_exams','appointments','lead_capture_forms',
    'notifications','notification_reads','student_notifications',
    'student_announcements','student_support_tickets','study_materials',
    'student_faqs','associates','associate_wallet_txns',
    'associate_notifications','associate_dispatches','wallet_recharge_requests',
    'associate_resources','associate_support_tickets','student_dispatches',
    'student_uploads','payroll','employees','attendance','leave_requests',
    'expenses','advance_salaries','department_litigations',
    'student_mentorships','revenue_targets'
  ] loop
    execute format('grant select, insert, update, delete on crm.%I to authenticated', t);
  end loop;
end $$;

grant usage, select on all sequences in schema crm to authenticated;

-- The public lead-capture page renders before login, so anon needs read on it.
-- Its policy already narrows that to `is_active = true`.
grant select on crm.lead_capture_forms to anon;

-- ------------------------------------------------------------------------
-- 0024_crm_service_role_grants.sql
-- ------------------------------------------------------------------------

-- Table grants for `service_role` in the crm schema.
--
-- In `public`, Supabase's bootstrap sets default privileges so service_role
-- gets every table automatically. A schema created by a migration inherits
-- none of that: 0008 granted `usage on schema crm` to service_role but never
-- any table, so every service-role request returned
--   42501  permission denied for table <t>
-- with RLS never even consulted. Caught against the live project the first
-- time the crm schema was exposed to the API.
--
-- The one caller this breaks is the bulk lead importer, which uses the service
-- role for its batch insert (`import-actions.ts`) — it would have failed on
-- the very first real import.

grant usage on schema crm to service_role;

grant select, insert, update, delete
  on all tables in schema crm to service_role;

grant usage, select on all sequences in schema crm to service_role;

-- `all tables in schema` only covers what exists right now. Default privileges
-- cover whatever a later migration adds, so this bug cannot come back.
alter default privileges in schema crm
  grant select, insert, update, delete on tables to service_role;

alter default privileges in schema crm
  grant usage, select on sequences to service_role;

-- Same reasoning for `authenticated`: 0008 and 0023 each had to list their own
-- tables by hand, and 0023 exists only because 0011-0022 were forgotten once.
alter default privileges in schema crm
  grant select, insert, update, delete on tables to authenticated;

alter default privileges in schema crm
  grant usage, select on sequences to authenticated;
