"""
Regenerates supabase/apply/*.sql — the two blocks pasted into the Supabase SQL
Editor to bring a live project up to date with the CRM migrations.

Why this exists rather than `supabase db push`: `migration repair` has never
been run on this project, so push will not apply the CRM files. The blocks are
hand-pasted instead, which means they must survive being run twice — a paste
that fails halfway has to be retriable. Postgres has no `create policy if not
exists`, no `create trigger if not exists` and no `add constraint if not
exists`, so this script inserts the matching DROP before each one.

    python3 scripts/build-apply-sql.py && node supabase/tests/apply-check.mjs
"""
import re, pathlib, textwrap

MIG = pathlib.Path("supabase/migrations")
OUT = pathlib.Path("supabase/apply"); OUT.mkdir(exist_ok=True)

# Block 1 is only ALTER TYPE. Postgres refuses to USE a new enum value in the
# transaction that ADDS it, and block 2's policies compare against all five.
BLOCK_A = ["0007_crm_roles.sql", "0009_crm_extra_roles.sql"]
BLOCK_B = ["0008_crm_schema.sql", "0010_student_metadata.sql",
    "0011_student_documents_exams.sql", "0012_appointments.sql",
    "0013_lead_capture_forms.sql", "0014_notifications.sql",
    "0015_student_portal.sql", "0016_associates_portal.sql",
    "0017_dispatches_uploads.sql", "0018_payroll.sql",
    "0019_hrms_employees.sql", "0020_department_litigations.sql",
    "0021_student_mentorships.sql", "0022_revenue_targets.sql",
    "0023_crm_grants.sql",
    "0024_crm_service_role_grants.sql"]

stats = {"policies": 0, "triggers": 0, "constraints": 0}
I = re.I | re.M


def guard(sql: str) -> str:
    # Policies built dynamically inside a do-block loop.
    def dyn(m):
        stats["policies"] += 1
        return (f"""'drop policy if exists "{m.group(1)}" on crm.%I', t);\n"""
                f"""    execute format(\n      'create policy "{m.group(1)}" on crm.%I{m.group(2)}""")
    sql = re.sub(r"""'create policy "([^"]+)" on crm\.%I(.*)""", dyn, sql, flags=I)

    # Plain policies; the name may be quoted or a bare identifier, and these
    # files mix upper- and lower-case SQL, hence re.I.
    def plain(m):
        stats["policies"] += 1
        name = m.group(2) or m.group(3)
        return f'{m.group(1)}drop policy if exists "{name}" on {m.group(4)};\n{m.group(0)}'
    sql = re.sub(
        r'^([ \t]*)create\s+policy\s+(?:"([^"]+)"|([a-zA-Z_]\w*))\s+on\s+([a-zA-Z_][\w.]*)',
        plain, sql, flags=I)

    # ALTER TABLE ... ADD CONSTRAINT has no IF NOT EXISTS either.
    def constraint(m):
        stats["constraints"] += 1
        return (f'{m.group(1)}alter table {m.group(2)} drop constraint if exists {m.group(3)};\n'
                f'{m.group(0)}')
    sql = re.sub(
        r'^([ \t]*)alter[ \t]+table[ \t]+([a-zA-Z_][\w.]*)\s*\n?\s*add[ \t]+constraint[ \t]+(\w+)',
        constraint, sql, flags=I)

    # Triggers that have no drop guard already above them.
    lines, out = sql.split("\n"), []
    for i, line in enumerate(lines):
        m = re.match(
            r'^([ \t]*)create\s+trigger\s+(\w+)\s+(?:before|after|instead of)\b.*?\son\s+([a-zA-Z_][\w.]*)',
            line, re.I)
        if m and not re.search(rf"drop\s+trigger\s+if\s+exists\s+{m.group(2)}\b",
                               "\n".join(lines[max(0, i - 3):i]), re.I):
            stats["triggers"] += 1
            out.append(f"{m.group(1)}drop trigger if exists {m.group(2)} on {m.group(3)};")
        out.append(line)
    return "\n".join(out)


def build(files, title, note):
    p = [f"-- {'=' * 74}\n-- {title}\n--\n",
         textwrap.indent(textwrap.fill(note, 72), "-- ") + "\n--\n",
         "-- Safe to run more than once: every CREATE is guarded, and every\n"
         "-- policy, trigger and constraint is dropped before it is recreated.\n"
         "--\n-- Generated by scripts/build-apply-sql.py — edit the migrations, not this.\n"
         f"-- {'=' * 74}\n\n"]
    for name in files:
        p.append(f"\n-- {'-' * 72}\n-- {name}\n-- {'-' * 72}\n\n"
                 f"{guard((MIG / name).read_text().rstrip())}\n")
    return "".join(p)


(OUT / "01-roles.sql").write_text(build(BLOCK_A,
    "CareerOptics CRM — BLOCK 1 of 2: role enum values",
    "Run this on its own and let it finish before running block 2. Postgres "
    "refuses to USE a new enum value in the same transaction that ADDS it, and "
    "block 2's RLS policies compare against all five of these roles."))
(OUT / "02-crm-schema.sql").write_text(build(BLOCK_B,
    "CareerOptics CRM — BLOCK 2 of 2: schema, RLS, triggers, grants",
    "Run this only after block 1 has completed. Creates the `crm` schema and "
    "everything in it: leads pipeline, students, payments, documents, "
    "appointments, notifications, the student and associate portals, HRMS, "
    "mentorships and revenue targets."))

print(f"guards added: {stats['policies']} policies, {stats['triggers']} triggers, "
      f"{stats['constraints']} constraints")
